services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: 'America/New_York'
      FTLCONF_webserver_api_password: ${WEBPASSWORD}
      FTLCONF_dns_upstreams: '172.20.0.3#5335'
      FTLCONF_dns_bogusPriv: 'true'
      FTLCONF_dns_domainNeeded: 'true'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      dns_net:
        ipv4_address: 172.20.0.2
      taurus:
    depends_on:
      unbound:
        condition: service_healthy

  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    restart: unless-stopped
    volumes:
      - './unbound/unbound.conf:/opt/unbound/etc/unbound/unbound.conf:ro'
      - './unbound/root.hints:/opt/unbound/etc/unbound/root.hints:ro'
    networks:
      dns_net:
        ipv4_address: 172.20.0.3
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "5335"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

networks:
  dns_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/29
  taurus:
    external: true
